name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy
    
    - name: Run flake8
      run: |
        flake8 he2plus --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 he2plus --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check he2plus || true
    
    - name: Check import sorting with isort
      run: |
        isort --check-only he2plus || true
    
    - name: Type check with mypy
      run: |
        mypy he2plus --ignore-missing-imports || true
