name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.3.0)'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine check-manifest
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        twine check dist/*
    
    - name: Test installation
      run: |
        pip install dist/*.whl
        he2plus --version
        he2plus list --available
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-dist
        path: dist/
  
  create-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-dist
        path: dist/
    
    - name: Get version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "tag=v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        name: Release ${{ steps.get_version.outputs.version }}
        body: |
          ## 🚀 he2plus ${{ steps.get_version.outputs.version }}
          
          ### ✨ What's New
          
          - Production-ready release
          - Validated with end-to-end testing
          - 12 development profiles available
          - Cross-platform support (macOS, Linux, Windows)
          
          ### 📦 Installation
          
          ```bash
          pip install git+https://github.com/he2plus/he2plus-lib.git@${{ steps.get_version.outputs.tag }}
          ```
          
          ### 🎯 Quick Start
          
          ```bash
          he2plus list --available
          he2plus info web-nextjs
          ```
          
          ### 📋 Changes
          
          See [CHANGELOG.md](https://github.com/he2plus/he2plus-lib/blob/main/CHANGELOG.md) for details.
          
          ### 🧪 Testing
          
          This release has been validated with comprehensive end-to-end testing.
          See [TEST_SUCCESS_REPORT.md](https://github.com/he2plus/he2plus-lib/blob/main/tests/e2e-fullstack/TEST_SUCCESS_REPORT.md).
        draft: false
        prerelease: false
        files: |
          dist/*
        generate_release_notes: true
  
  publish-pypi:
    needs: create-release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-dist
        path: dist/
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
